def help():
    print("i can: ")
    print("calculate between two numbers(calculate)")
    print("remember one thing(remember)(give) for giving information that needs to be stored")
    print("or take to take back the information. (Exit) to exit the remember part of it.")
    print("greet (hello)")
    print("(news) to see the head lines")
    print("want to play a game of toss(toss)")
    print("want to draw (draw)")
    print("to exit(exit) or (bye)")
    print("go to google(google)")
    print("listen to music(music)")
    print("to see date and time(date) or (time)")
    print("to see the weather of a place(weather)")
